name: K6LoadPerformance
on:
  workflow_dispatch:
    inputs:
      TARGET_VUS:
        type: string
        description: Total Virtual Users
        required: true
jobs:
  test-acction:
    runs-on: ubuntu-latest
    steps:
        - name: Clone repository
          uses: actions/checkout@main
        - name: Intalling  GPG
          run: sudo gpg -k 
        - name: Installing Keys
          run: sudo gpg --no-default-keyring --keyring /usr/share/keyrings/k6-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
        - name: Source List
          run: echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
        - name: Update APT
          run: sudo apt-get update
        - name: Install K6
          run: sudo apt-get install k6
        - name: Run K6
          run: k6 run /home/runner/work/k6perf/smoke-test.js